// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package reaction

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*FollowReactionOperator).PreRun) // from handler/larkhandler/reaction/follow_react.go:35
	reflecting.GetFunctionName((*FollowReactionOperator).Run)    // from handler/larkhandler/reaction/follow_react.go:47
	reflecting.GetFunctionName((*RecordReactionOperator).PreRun) // from handler/larkhandler/reaction/record_reaction.go:36
	reflecting.GetFunctionName((*RecordReactionOperator).Run)    // from handler/larkhandler/reaction/record_reaction.go:48
}
