// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package copywriting

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetCopyWritings)       // from utility/copywriting/copywriting.go:25
	reflecting.GetFunctionName(GetSampleCopyWritings) // from utility/copywriting/copywriting.go:65
}
