// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package larkimg

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(DownImgFromMsgAsync)      // from utility/larkutils/larkimg/img.go:108
	reflecting.GetFunctionName(DownImgFromMsgSync)       // from utility/larkutils/larkimg/img.go:41
	reflecting.GetFunctionName(GetAllImageFromMsgEvent)  // from utility/larkutils/larkimg/img.go:272
	reflecting.GetFunctionName(GetAllImgTagFromMsg)      // from utility/larkutils/larkimg/img.go:234
	reflecting.GetFunctionName(GetAndResizePicFromURL)   // from utility/larkutils/larkimg/img.go:406
	reflecting.GetFunctionName(Upload2Lark)              // from utility/larkutils/larkimg/img.go:484
	reflecting.GetFunctionName(UploadPicAllinOne)        // from utility/larkutils/larkimg/img.go:435
	reflecting.GetFunctionName(UploadPicture2Lark)       // from utility/larkutils/larkimg/img.go:543
	reflecting.GetFunctionName(UploadPicture2LarkReader) // from utility/larkutils/larkimg/img.go:517
	reflecting.GetFunctionName(getAllImage)              // from utility/larkutils/larkimg/img.go:306
}
