// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package message

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(SendAndReplyStreamingCard)  // from utility/message/cardmessage.go:97
	reflecting.GetFunctionName(SendAndUpdateStreamingCard) // from utility/message/cardmessage.go:27
	reflecting.GetFunctionName(updateCardFunc)             // from utility/message/cardmessage.go:172, utility/message/cardmessage.go:182, utility/message/cardmessage.go:208
}
