// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package handlers

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(ChatHandlerInner)       // from handler/larkhandler/lark_command/handlers/chat_handler.go:45
	reflecting.GetFunctionName(DebugGetGroupIDHandler) // from handler/larkhandler/lark_command/handlers/debug_handler.go:70
	reflecting.GetFunctionName(DebugGetIDHandler)      // from handler/larkhandler/lark_command/handlers/debug_handler.go:45
	reflecting.GetFunctionName(DebugImageHandler)      // from handler/larkhandler/lark_command/handlers/debug_handler.go:308
	reflecting.GetFunctionName(DebugRepeatHandler)     // from handler/larkhandler/lark_command/handlers/debug_handler.go:264
	reflecting.GetFunctionName(DebugRevertHandler)     // from handler/larkhandler/lark_command/handlers/debug_handler.go:223
	reflecting.GetFunctionName(DebugTraceHandler)      // from handler/larkhandler/lark_command/handlers/debug_handler.go:159
	reflecting.GetFunctionName(DebugTryPanicHandler)   // from handler/larkhandler/lark_command/handlers/debug_handler.go:94
	reflecting.GetFunctionName(GenerateChatSeq)        // from handler/larkhandler/lark_command/handlers/chat_handler.go:109
	reflecting.GetFunctionName(GetTraceFromMsgID)      // from handler/larkhandler/lark_command/handlers/debug_handler.go:113
	reflecting.GetFunctionName(GoldHandler)            // from handler/larkhandler/lark_command/handlers/stock_handler.go:29
	reflecting.GetFunctionName(ImageAddHandler)        // from handler/larkhandler/lark_command/handlers/image_handler.go:33
	reflecting.GetFunctionName(ImageDelHandler)        // from handler/larkhandler/lark_command/handlers/image_handler.go:155
	reflecting.GetFunctionName(ImageGetHandler)        // from handler/larkhandler/lark_command/handlers/image_handler.go:115
	reflecting.GetFunctionName(ImitateHandler)         // from handler/larkhandler/lark_command/handlers/imitate_handler.go:25
	reflecting.GetFunctionName(MusicSearchHandler)     // from handler/larkhandler/lark_command/handlers/music_handler.go:19
	reflecting.GetFunctionName(MuteHandler)            // from handler/larkhandler/lark_command/handlers/mute_handler.go:20
	reflecting.GetFunctionName(OneWordHandler)         // from handler/larkhandler/lark_command/handlers/oneword_handler.go:37
	reflecting.GetFunctionName(ReplyGetHandler)        // from handler/larkhandler/lark_command/handlers/reply_handler.go:123
	reflecting.GetFunctionName(StatsGetHandler)        // from handler/larkhandler/lark_command/handlers/stats_handler.go:14
	reflecting.GetFunctionName(WordAddHandler)         // from handler/larkhandler/lark_command/handlers/word_handler.go:30
	reflecting.GetFunctionName(WordGetHandler)         // from handler/larkhandler/lark_command/handlers/word_handler.go:68
}
