// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package aktool

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetHistoryGoldPrice)  // from dal/aktool/aktool.go:79
	reflecting.GetFunctionName(GetRealtimeGoldPrice) // from dal/aktool/aktool.go:46
	reflecting.GetFunctionName(GetStockPriceRT)      // from dal/aktool/aktool.go:111
	reflecting.GetFunctionName(GetStockSymbolInfo)   // from dal/aktool/aktool.go:137
}
