// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package admin

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(AddAdminHandler)         // from handler/commandHandler/admin/admin.go:111
	reflecting.GetFunctionName(DeleteAllMessageHandler) // from handler/commandHandler/admin/admin.go:300
	reflecting.GetFunctionName(Handler)                 // from handler/commandHandler/admin/notify.go:14
	reflecting.GetFunctionName(ReconnectHandler)        // from handler/commandHandler/admin/admin.go:375
	reflecting.GetFunctionName(RemoveAdminHandler)      // from handler/commandHandler/admin/admin.go:210
	reflecting.GetFunctionName(ShowAdminHandler)        // from handler/commandHandler/admin/admin.go:27
}
