// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package news

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(Handler)        // from handler/commandHandler/news/handler.go:56
	reflecting.GetFunctionName(MorningHandler) // from handler/commandHandler/news/handler.go:161
}
