// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package message

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*ChatMsgOperator).PreRun)      // from handler/larkhandler/message/chat_op.go:39
	reflecting.GetFunctionName((*ChatMsgOperator).Run)         // from handler/larkhandler/message/chat_op.go:60
	reflecting.GetFunctionName((*CommandOperator).PreRun)      // from handler/larkhandler/message/command_op.go:38
	reflecting.GetFunctionName((*CommandOperator).Run)         // from handler/larkhandler/message/command_op.go:55
	reflecting.GetFunctionName((*ReactMsgOperator).PreRun)     // from handler/larkhandler/message/react_op.go:35
	reflecting.GetFunctionName((*ReactMsgOperator).Run)        // from handler/larkhandler/message/react_op.go:53
	reflecting.GetFunctionName((*RecordMsgOperator).PreRun)    // from handler/larkhandler/message/record_op.go:32
	reflecting.GetFunctionName((*RecordMsgOperator).Run)       // from handler/larkhandler/message/record_op.go:47
	reflecting.GetFunctionName((*RepeatMsgOperator).PreRun)    // from handler/larkhandler/message/repeat_op.go:42
	reflecting.GetFunctionName((*RepeatMsgOperator).Run)       // from handler/larkhandler/message/repeat_op.go:63
	reflecting.GetFunctionName((*ReplyChatOperator).PreRun)    // from handler/larkhandler/message/reply_chat_op.go:39
	reflecting.GetFunctionName((*ReplyChatOperator).Run)       // from handler/larkhandler/message/reply_chat_op.go:57
	reflecting.GetFunctionName((*WordReplyMsgOperator).PreRun) // from handler/larkhandler/message/word_reply_op.go:41
	reflecting.GetFunctionName((*WordReplyMsgOperator).Run)    // from handler/larkhandler/message/word_reply_op.go:63, handler/larkhandler/message/word_reply_op.go:100
	reflecting.GetFunctionName(CollectMessage)                 // from handler/larkhandler/message/base.go:34
}
