// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package manager

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(ChannelJoinedAsyncHandler) // from handler/manager/manager.go:56
	reflecting.GetFunctionName(ChannelLeftAsyncHandler)   // from handler/manager/manager.go:75
	reflecting.GetFunctionName(ClickEventAsyncHandler)    // from handler/manager/manager.go:87
	reflecting.GetFunctionName(CommandHandler)            // from handler/manager/manager.go:24
	reflecting.GetFunctionName(MessageEventAsyncHandler)  // from handler/manager/manager.go:99
	reflecting.GetFunctionName(clickEventHandler)         // from handler/manager/handlers.go:28
	reflecting.GetFunctionName(messageEventHandler)       // from handler/manager/handlers.go:267
}
