// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package manager

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(ChannelJoinedAsyncHandler) // from handler/manager/manager.go:55
	reflecting.GetFunctionName(ChannelLeftAsyncHandler)   // from handler/manager/manager.go:74
	reflecting.GetFunctionName(ClickEventAsyncHandler)    // from handler/manager/manager.go:86
	reflecting.GetFunctionName(CommandHandler)            // from handler/manager/manager.go:23
	reflecting.GetFunctionName(MessageEventAsyncHandler)  // from handler/manager/manager.go:98
	reflecting.GetFunctionName(clickEventHandler)         // from handler/manager/handlers.go:27
	reflecting.GetFunctionName(messageEventHandler)       // from handler/manager/handlers.go:266
}
