// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package opensearchdal

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(InsertData)    // from utility/opensearch_dal/client.go:49
	reflecting.GetFunctionName(SearchData)    // from utility/opensearch_dal/client.go:67
	reflecting.GetFunctionName(SearchDataStr) // from utility/opensearch_dal/client.go:81
}
