// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package retriver

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*RAGSystem).AddDocuments) // from utility/retriver/retriver.go:130
	reflecting.GetFunctionName(NewRAGSystem)              // from utility/retriver/retriver.go:78
}
