// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package qqmusicapi

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*QQmusicContext).GetMusicURLByID) // from dal/qqmusicapi/qqmusic.go:104
	reflecting.GetFunctionName((*QQmusicContext).SearchMusic)     // from dal/qqmusicapi/qqmusic.go:52
}
