// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package tools

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(CallFunction) // from utility/ark/tools/tools.go:19
}
