// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package gpt3

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(ClientHandler)             // from handler/commandHandler/gpt3/handler.go:430
	reflecting.GetFunctionName(ClientHandlerStream)       // from handler/commandHandler/gpt3/handler.go:63, handler/commandHandler/gpt3/handler.go:129
	reflecting.GetFunctionName(ClientHandlerStreamUpdate) // from handler/commandHandler/gpt3/handler.go:219, handler/commandHandler/gpt3/handler.go:272
}
