// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package larkhandler

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetCardMusicByPage)     // from handler/larkhandler/webhook_handler.go:62
	reflecting.GetFunctionName(HandleFullLyrics)       // from handler/larkhandler/webhook_handler.go:202
	reflecting.GetFunctionName(MessageReactionHandler) // from handler/larkhandler/message_handler.go:58
	reflecting.GetFunctionName(MessageV2Handler)       // from handler/larkhandler/message_handler.go:34
	reflecting.GetFunctionName(SendAlbumCard)          // from handler/larkhandler/webhook_handler.go:176
	reflecting.GetFunctionName(SendMusicCard)          // from handler/larkhandler/webhook_handler.go:164
	reflecting.GetFunctionName(WebHookHandler)         // from handler/larkhandler/webhook_handler.go:25
}
