// Code generated by warmup; DO NOT EDIT.
package main

import (
	neteaseapi "github.com/BetaGoRobot/BetaGo/dal/neteaseapi"
	qqmusicapi "github.com/BetaGoRobot/BetaGo/dal/qqmusicapi"
	larkhandler "github.com/BetaGoRobot/BetaGo/handler/larkhandler"
	handlers "github.com/BetaGoRobot/BetaGo/handler/larkhandler/lark_command/handlers"
	reaction "github.com/BetaGoRobot/BetaGo/handler/larkhandler/reaction"
	copywriting "github.com/BetaGoRobot/BetaGo/utility/copywriting"
	doubao "github.com/BetaGoRobot/BetaGo/utility/doubao"
	larkutils "github.com/BetaGoRobot/BetaGo/utility/larkutils"
	message "github.com/BetaGoRobot/BetaGo/handler/larkhandler/message"
	miniohelper "github.com/BetaGoRobot/BetaGo/utility/minio_helper"
	opensearchdal "github.com/BetaGoRobot/BetaGo/utility/opensearch_dal"
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*message.ChatMsgOperator).PreRun)                 // from handler/larkhandler/message/chat_op.go:39
	reflecting.GetFunctionName((*message.ChatMsgOperator).Run)                    // from handler/larkhandler/message/chat_op.go:60
	reflecting.GetFunctionName((*message.CommandOperator).PreRun)                 // from handler/larkhandler/message/command_op.go:38
	reflecting.GetFunctionName((*message.CommandOperator).Run)                    // from handler/larkhandler/message/command_op.go:55
	reflecting.GetFunctionName((*message.ReactMsgOperator).PreRun)                // from handler/larkhandler/message/react_op.go:35
	reflecting.GetFunctionName((*message.ReactMsgOperator).Run)                   // from handler/larkhandler/message/react_op.go:53
	reflecting.GetFunctionName((*message.RepeatMsgOperator).PreRun)               // from handler/larkhandler/message/repeat_op.go:42
	reflecting.GetFunctionName((*message.RepeatMsgOperator).Run)                  // from handler/larkhandler/message/repeat_op.go:63
	reflecting.GetFunctionName((*message.ReplyChatOperator).PreRun)               // from handler/larkhandler/message/reply_chat_op.go:39
	reflecting.GetFunctionName((*message.ReplyChatOperator).Run)                  // from handler/larkhandler/message/reply_chat_op.go:57
	reflecting.GetFunctionName((*message.WordReplyMsgOperator).PreRun)            // from handler/larkhandler/message/word_reply_op.go:41
	reflecting.GetFunctionName((*message.WordReplyMsgOperator).Run)               // from handler/larkhandler/message/word_reply_op.go:63, handler/larkhandler/message/word_reply_op.go:100
	reflecting.GetFunctionName((*miniohelper.MinioManager).PresignURL)            // from utility/minio_helper/helper.go:274
	reflecting.GetFunctionName((*miniohelper.MinioManager).TryGetFile)            // from utility/minio_helper/helper.go:252
	reflecting.GetFunctionName((*miniohelper.MinioManager).UploadFile)            // from utility/minio_helper/helper.go:262
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).CheckIfLogin)         // from dal/neteaseapi/auth.go:257
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetAlbumDetail)       // from dal/neteaseapi/netease.go:487
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetComment)           // from dal/neteaseapi/netease.go:577
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetDetail)            // from dal/neteaseapi/netease.go:257
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetLyrics)            // from dal/neteaseapi/netease.go:298
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetMusicURL)          // from dal/neteaseapi/netease.go:223
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetMusicURLByID)      // from dal/neteaseapi/netease.go:177
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetMusicURLByIDs)     // from dal/neteaseapi/netease.go:113
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).LoginNetEase)         // from dal/neteaseapi/auth.go:211
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).LoginNetEaseQR)       // from dal/neteaseapi/auth.go:170
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).RefreshLogin)         // from dal/neteaseapi/auth.go:33
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).SaveCookie)           // from dal/neteaseapi/auth.go:320
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).SearchAlbumByKeyWord) // from dal/neteaseapi/netease.go:451
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).SearchMusicByKeyWord) // from dal/neteaseapi/netease.go:407
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).TryGetLastCookie)     // from dal/neteaseapi/auth.go:290
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).InnerAsyncGetSearchRes)    // from dal/neteaseapi/netease.go:548
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetQRBase64)          // from dal/neteaseapi/auth.go:91
	reflecting.GetFunctionName((*neteaseapi.NetEaseContext).GetUniKey)            // from dal/neteaseapi/auth.go:70
	reflecting.GetFunctionName((*qqmusicapi.QQmusicContext).GetMusicURLByID)      // from dal/qqmusicapi/qqmusic.go:104
	reflecting.GetFunctionName((*qqmusicapi.QQmusicContext).SearchMusic)          // from dal/qqmusicapi/qqmusic.go:52
	reflecting.GetFunctionName((*reaction.FollowReactionOperator).PreRun)         // from handler/larkhandler/reaction/follow_react.go:35
	reflecting.GetFunctionName((*reaction.FollowReactionOperator).Run)            // from handler/larkhandler/reaction/follow_react.go:47
	reflecting.GetFunctionName((*reaction.RecordReactionOperator).PreRun)         // from handler/larkhandler/reaction/record_reaction.go:36
	reflecting.GetFunctionName((*reaction.RecordReactionOperator).Run)            // from handler/larkhandler/reaction/record_reaction.go:48
	reflecting.GetFunctionName(copywriting.GetCopyWritings)                       // from utility/copywriting/copywriting.go:25
	reflecting.GetFunctionName(copywriting.GetSampleCopyWritings)                 // from utility/copywriting/copywriting.go:65
	reflecting.GetFunctionName(doubao.EmbeddingText)                              // from utility/doubao/embedding.go:35
	reflecting.GetFunctionName(doubao.GenerateChat)                               // from utility/doubao/tools.go:11
	reflecting.GetFunctionName(doubao.SingleChat)                                 // from utility/doubao/embedding.go:58
	reflecting.GetFunctionName(doubao.SingleChatModel)                            // from utility/doubao/embedding.go:113
	reflecting.GetFunctionName(doubao.SingleChatPrompt)                           // from utility/doubao/embedding.go:89
	reflecting.GetFunctionName(doubao.SingleChatStreamingPrompt)                  // from utility/doubao/embedding.go:149
	reflecting.GetFunctionName(handlers.ChatHandlerInner)                         // from handler/larkhandler/lark_command/handlers/chat_handler.go:38
	reflecting.GetFunctionName(handlers.DebugGetGroupIDHandler)                   // from handler/larkhandler/lark_command/handlers/debug_handler.go:67
	reflecting.GetFunctionName(handlers.DebugGetIDHandler)                        // from handler/larkhandler/lark_command/handlers/debug_handler.go:42
	reflecting.GetFunctionName(handlers.DebugRepeatHandler)                       // from handler/larkhandler/lark_command/handlers/debug_handler.go:257
	reflecting.GetFunctionName(handlers.DebugRevertHandler)                       // from handler/larkhandler/lark_command/handlers/debug_handler.go:216
	reflecting.GetFunctionName(handlers.DebugTraceHandler)                        // from handler/larkhandler/lark_command/handlers/debug_handler.go:152
	reflecting.GetFunctionName(handlers.DebugTryPanicHandler)                     // from handler/larkhandler/lark_command/handlers/debug_handler.go:91
	reflecting.GetFunctionName(handlers.GenerateChatReply)                        // from handler/larkhandler/lark_command/handlers/chat_handler.go:232
	reflecting.GetFunctionName(handlers.GenerateChatSeq)                          // from handler/larkhandler/lark_command/handlers/chat_handler.go:180
	reflecting.GetFunctionName(handlers.GetTraceFromMsgID)                        // from handler/larkhandler/lark_command/handlers/debug_handler.go:110
	reflecting.GetFunctionName(handlers.ImageAddHandler)                          // from handler/larkhandler/lark_command/handlers/image_handler.go:33
	reflecting.GetFunctionName(handlers.ImageDelHandler)                          // from handler/larkhandler/lark_command/handlers/image_handler.go:157
	reflecting.GetFunctionName(handlers.ImageGetHandler)                          // from handler/larkhandler/lark_command/handlers/image_handler.go:115
	reflecting.GetFunctionName(handlers.ImitateHandler)                           // from handler/larkhandler/lark_command/handlers/imitate_handler.go:23
	reflecting.GetFunctionName(handlers.MusicSearchHandler)                       // from handler/larkhandler/lark_command/handlers/music_handler.go:19
	reflecting.GetFunctionName(handlers.MuteHandler)                              // from handler/larkhandler/lark_command/handlers/mute_handler.go:20
	reflecting.GetFunctionName(handlers.OneWordHandler)                           // from handler/larkhandler/lark_command/handlers/oneword_handler.go:37
	reflecting.GetFunctionName(handlers.ReplyGetHandler)                          // from handler/larkhandler/lark_command/handlers/reply_handler.go:123
	reflecting.GetFunctionName(handlers.StatsGetHandler)                          // from handler/larkhandler/lark_command/handlers/stats_handler.go:14
	reflecting.GetFunctionName(handlers.WordAddHandler)                           // from handler/larkhandler/lark_command/handlers/word_handler.go:30
	reflecting.GetFunctionName(handlers.WordGetHandler)                           // from handler/larkhandler/lark_command/handlers/word_handler.go:68
	reflecting.GetFunctionName(larkhandler.GetCardMusicByPage)                    // from handler/larkhandler/webhook_handler.go:62
	reflecting.GetFunctionName(larkhandler.HandleFullLyrics)                      // from handler/larkhandler/webhook_handler.go:202
	reflecting.GetFunctionName(larkhandler.MessageReactionHandler)                // from handler/larkhandler/message_handler.go:57
	reflecting.GetFunctionName(larkhandler.MessageV2Handler)                      // from handler/larkhandler/message_handler.go:34
	reflecting.GetFunctionName(larkhandler.SendAlbumCard)                         // from handler/larkhandler/webhook_handler.go:176
	reflecting.GetFunctionName(larkhandler.SendMusicCard)                         // from handler/larkhandler/webhook_handler.go:164
	reflecting.GetFunctionName(larkhandler.WebHookHandler)                        // from handler/larkhandler/webhook_handler.go:25
	reflecting.GetFunctionName(larkutils.AddReaction)                             // from utility/larkutils/msg.go:387
	reflecting.GetFunctionName(larkutils.AddReaction2DB)                          // from utility/larkutils/msg.go:181
	reflecting.GetFunctionName(larkutils.AddReactionAsync)                        // from utility/larkutils/msg.go:406
	reflecting.GetFunctionName(larkutils.CreateMsgText)                           // from utility/larkutils/msg.go:343
	reflecting.GetFunctionName(larkutils.CreateMsgTextRaw)                        // from utility/larkutils/msg.go:353
	reflecting.GetFunctionName(larkutils.GenFullLyricsCard)                       // from utility/larkutils/cards.go:251
	reflecting.GetFunctionName(larkutils.GenerateMusicCardByStruct)               // from utility/larkutils/cards.go:276
	reflecting.GetFunctionName(larkutils.GetChatIDFromMsgID)                      // from utility/larkutils/lark.go:280
	reflecting.GetFunctionName(larkutils.GetChatName)                             // from utility/larkutils/lark.go:264
	reflecting.GetFunctionName(larkutils.GetUserMapFromChatID)                    // from utility/larkutils/lark.go:220
	reflecting.GetFunctionName(larkutils.GetUserMemberFromChat)                   // from utility/larkutils/lark.go:253
	reflecting.GetFunctionName(larkutils.NewSheetCardContent)                     // from utility/larkutils/card_helper.go:52
	reflecting.GetFunctionName(larkutils.PreGetTextMsg)                           // from utility/larkutils/msg.go:41
	reflecting.GetFunctionName(larkutils.RecordMessage2Opensearch)                // from utility/larkutils/msg.go:250
	reflecting.GetFunctionName(larkutils.RecordReplyMessage2Opensearch)           // from utility/larkutils/msg.go:296
	reflecting.GetFunctionName(larkutils.RemoveReaction)                          // from utility/larkutils/msg.go:427
	reflecting.GetFunctionName(larkutils.ReplyCard)                               // from utility/larkutils/reply.go:20
	reflecting.GetFunctionName(larkutils.ReplyCardText)                           // from utility/larkutils/reply.go:56
	reflecting.GetFunctionName(larkutils.ReplyMsgRawContentType)                  // from utility/larkutils/msg.go:194
	reflecting.GetFunctionName(larkutils.ReplyMsgText)                            // from utility/larkutils/msg.go:243
	reflecting.GetFunctionName(larkutils.TrimAtMsg)                               // from utility/larkutils/msg.go:74
	reflecting.GetFunctionName(larkutils.Upload2Lark)                             // from utility/larkutils/lark.go:108
	reflecting.GetFunctionName(larkutils.UploadPicAllinOne)                       // from utility/larkutils/lark.go:59
	reflecting.GetFunctionName(larkutils.UploadPicture2Lark)                      // from utility/larkutils/lark.go:167
	reflecting.GetFunctionName(larkutils.UploadPicture2LarkReader)                // from utility/larkutils/lark.go:141
	reflecting.GetFunctionName(larkutils.GetAndResizePicFromURL)                  // from utility/larkutils/lark.go:30
	reflecting.GetFunctionName(message.CollectMessage)                            // from handler/larkhandler/message/base.go:33
	reflecting.GetFunctionName(miniohelper.MinioCheckFileExists)                  // from utility/minio_helper/uploads.go:67
	reflecting.GetFunctionName(miniohelper.MinioTryGetFile)                       // from utility/minio_helper/uploads.go:56
	
	
	
	reflecting.GetFunctionName(opensearchdal.InsertData)                          // from utility/opensearch_dal/client.go:44
	reflecting.GetFunctionName(opensearchdal.SearchData)                          // from utility/opensearch_dal/client.go:58
}
