// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package helper

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(AdminCommandHelperHandler) // from handler/commandHandler/helper/helper.go:58
	reflecting.GetFunctionName(GetUserInfoHandler)        // from handler/commandHandler/helper/user.go:21
	reflecting.GetFunctionName(PingHandler)               // from handler/commandHandler/helper/ping.go:20
	reflecting.GetFunctionName(TryPanic)                  // from handler/commandHandler/helper/helper.go:27
	reflecting.GetFunctionName(UserCommandHelperHandler)  // from handler/commandHandler/helper/helper.go:220
}
