// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package doubao

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(EmbeddingText)             // from utility/doubao/embedding.go:39
	reflecting.GetFunctionName(GenerateChat)              // from utility/doubao/tools.go:11
	reflecting.GetFunctionName(ResponseWithCache)         // from utility/doubao/embedding.go:62
	reflecting.GetFunctionName(SingleChatStreamingPrompt) // from utility/doubao/embedding.go:153, utility/doubao/embedding.go:209
}
