// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package grouputil

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(GetUserMapFromChatID)  // from utility/larkutils/grouputil/group.go:33
	reflecting.GetFunctionName(GetUserMemberFromChat) // from utility/larkutils/grouputil/group.go:15
}
