// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package neteaseapi

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*NetEaseContext).CheckIfLogin)           // from dal/neteaseapi/auth.go:257
	reflecting.GetFunctionName((*NetEaseContext).GetAlbumDetail)         // from dal/neteaseapi/netease.go:487
	reflecting.GetFunctionName((*NetEaseContext).GetComment)             // from dal/neteaseapi/netease.go:577
	reflecting.GetFunctionName((*NetEaseContext).GetDetail)              // from dal/neteaseapi/netease.go:257
	reflecting.GetFunctionName((*NetEaseContext).GetLyrics)              // from dal/neteaseapi/netease.go:298
	reflecting.GetFunctionName((*NetEaseContext).GetMusicURL)            // from dal/neteaseapi/netease.go:223
	reflecting.GetFunctionName((*NetEaseContext).GetMusicURLByID)        // from dal/neteaseapi/netease.go:177
	reflecting.GetFunctionName((*NetEaseContext).GetMusicURLByIDs)       // from dal/neteaseapi/netease.go:113
	reflecting.GetFunctionName((*NetEaseContext).GetQRBase64)            // from dal/neteaseapi/auth.go:91
	reflecting.GetFunctionName((*NetEaseContext).GetUniKey)              // from dal/neteaseapi/auth.go:70
	reflecting.GetFunctionName((*NetEaseContext).InnerAsyncGetSearchRes) // from dal/neteaseapi/netease.go:548
	reflecting.GetFunctionName((*NetEaseContext).LoginNetEase)           // from dal/neteaseapi/auth.go:211
	reflecting.GetFunctionName((*NetEaseContext).LoginNetEaseQR)         // from dal/neteaseapi/auth.go:170
	reflecting.GetFunctionName((*NetEaseContext).RefreshLogin)           // from dal/neteaseapi/auth.go:33
	reflecting.GetFunctionName((*NetEaseContext).SaveCookie)             // from dal/neteaseapi/auth.go:320
	reflecting.GetFunctionName((*NetEaseContext).SearchAlbumByKeyWord)   // from dal/neteaseapi/netease.go:451
	reflecting.GetFunctionName((*NetEaseContext).SearchMusicByKeyWord)   // from dal/neteaseapi/netease.go:407
	reflecting.GetFunctionName((*NetEaseContext).TryGetLastCookie)       // from dal/neteaseapi/auth.go:290
	reflecting.GetFunctionName(asyncUploadPics)                          // from dal/neteaseapi/netease.go:514
	reflecting.GetFunctionName(qrImgReadCloser)                          // from dal/neteaseapi/auth.go:197
	reflecting.GetFunctionName(uploadMusic)                              // from dal/neteaseapi/netease.go:150
}
