// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package history

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName((*Helper).GetAll)   // from utility/history/msg.go:157
	reflecting.GetFunctionName((*Helper).GetMsg)   // from utility/history/msg.go:124
	reflecting.GetFunctionName((*Helper).GetRaw)   // from utility/history/msg.go:137
	reflecting.GetFunctionName((*Helper).GetTrend) // from utility/history/msg.go:211
	reflecting.GetFunctionName(HybridSearch)       // from utility/history/search.go:50
}
