// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.
// Code generated by warmup_gen.go; DO NOT EDIT.

package cal

import (
	"github.com/BetaGoRobot/go_utils/reflecting"
)

func init() {
	reflecting.GetFunctionName(DrawPieChartWithAPI)    // from handler/commandHandler/cal/cal.go:348
	reflecting.GetFunctionName(DrawPieChartWithLocal)  // from handler/commandHandler/cal/cal.go:509
	reflecting.GetFunctionName(DrawPieChartWithLocal1) // from handler/commandHandler/cal/cal.go:437
	reflecting.GetFunctionName(GetUserChannelTimeMap)  // from handler/commandHandler/cal/cal.go:306
	reflecting.GetFunctionName(ShowCalHandler)         // from handler/commandHandler/cal/cal.go:145
	reflecting.GetFunctionName(ShowCalLocalHandler)    // from handler/commandHandler/cal/cal.go:232
}
